title: DooDoo
email: doododotio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of simple tools built with very little code and lots  and lots of love.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: doododotio
github_username:  dsmoore

sass:
  style: compressed

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
